// React-ts/View/$$name.pascal$$View.tsx
import './$$name.pascal$$View.scss';

/**
 * This is the $$name.pascal$$View
 * @author $$git-name$$
 * @version 1.0.0
 * @created $$year$$-$$month$$-$$day$$
 */
function $$name.pascal$$View() {
    return (
        <div className="content">
            <div className="$$name.kebab$$">
                <h1>Welcome to the $$name.pascal$$View!</h1>
                {/* Add your content here */}
            </div>
        </div>
    );
}

export default $$name.pascal$$View;

// Vue3/View/$$name.pascal$$View.vue
<script lang="ts">
export default {
    name: '$$name.pascal$$View',
    data() {
        return {};
    },
    methods: {},
};
</script>

<template>
    <div class="content">
        <h1>Welcome to the $$name.pascal$$View!</h1>
    </div>
</template>

<style scoped lang="scss">
@import '@/variables';
</style>
