// React-js/Component/$$name.pascal$$.jsx
import './$$name.pascal$$.scss';

/**
 * This is a $$name.pascal$$ component
 * @author $$git-name$$
 * @version 1.0.0
 * @created $$year$$-$$month$$-$$day$$
 */
function $$name.pascal$$() {
    return <div className="$$name.kebab$$">Hello from $$name.pascal$$</div>;
}
export default $$name.pascal$$;

// Vue3/Component/$$name.pascal$$.vue
<script lang="ts">
export default {
    name: '$$name.pascal$$',
    data() {
        return {};
    },
    methods: {},
};
</script>

<template>
    <div class="$$name.kebab$$">
        <p>Hello from $$name.pascal$$</p>
    </div>
</template>

<style scoped lang="scss">
@import '@/variables';

.$$name.kebab$$ {
}
</style>
